@MeraStore.Service.Logging_HostAddress = http://localhost:5286

### Log a Request
POST {{MeraStore.Service.Logging_HostAddress}}/api/requestlogs
Content-Type: application/json
Accept: application/json

{
    "apiEndpoint": "/api/weatherforecast",
    "requestContent": "{ 'param1': 'value1', 'param2': 'value2' }",
    "timestamp": "2024-10-02T12:00:00Z"
}

### Log a Response
POST {{MeraStore.Service.Logging_HostAddress}}/api/responses
Content-Type: application/json
Accept: application/json

{
    "apiEndpoint": "/api/weatherforecast",
    "responseContent": "{ 'temperature': 22, 'condition': 'Sunny' }",
    "timestamp": {}
}

### Get Request Log by Id
GET {{MeraStore.Service.Logging_HostAddress}}/api/requests/{id}
Accept: application/json

### Get Response Log by Id
GET {{MeraStore.Service.Logging_HostAddress}}/api/responses/{id}
Accept: application/json
